### ISSUE TITLE
Use with changefeeds?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [tjmehta/rethinkdb-observable#3]
Does this work with changefeeds?

**Comment by tjmehta** [comment]
Yup, works with all rethinkdb cursors

**Comment by GeoffreyPlitt** [comment]
Well, changefeeds have no end/close, so would the onCompleted() ever get called?

I'd like to use the toArray() behavior of non-changefeed-cursors, but with changefeeds, instead of using each() logic.

**Comment by tjmehta** [comment]
Exactly! 'onCompleted' will never be called with changefeed cursors. You will have to dispose the subscription to close the cursor. Also keep in mind, this inherits from the base Observable (not ConnectableObservable). I am not sure if your familiar with connectable observables and rxjs. To subscribe to the observable multiple times you'll probably use 'publish().refCount()'.

**Comment by GeoffreyPlitt** [comment]
Gotcha, thanks.

**Comment by tjmehta** [comment]
I don't fully understand what you're wanting out of toArray(), but assuming you know some scenario where you want to stop listening to the changefeed.. I'm sure there is an rxjs observable operator that trigger 'completed' after it receives a certain number of results or passes some test.

**Comment by tjmehta** [comment]
Or obviously, just unsubscribe after you get the last result you want.
